### ISSUE TITLE
Project links

### ISSUE THREAD

**Issue by luaneyed** [sparcs-kaist/sparcs_home#13]
- [ ] GenChem
- [ ] 넙죽이
- [ ] New Ara
- [ ] Zabo
- [x] SPARCS SSO
- [x] SPARCS 09
- [x] Nugu
- [ ] OTL PLUS
- [ ] ARA
- [ ] 거울
- [ ] Heartbeat

**Comment by luaneyed** [comment]
ex)
프로젝트 : nugu
Github 1 : https://github.com/sparcs-kaist/nugu
Github 2 : https://github.com/sparcs-kaist/nugu-api

**Comment by sugoiii** [comment]
프로젝트 : SPARCS 09
Web : https://09.sparcs.org/
Github : https://github.com/sparcs-kaist/sparcs09

**Comment by Sanghou** [comment]
프로젝트 : SPARCS SSO
Web : https://sparcssso.kaist.ac.kr/
Github : https://github.com/sparcs-kaist/sparcssso
