### ISSUE TITLE
Cannot download recent seminars

### ISSUE THREAD

**Issue by luaneyed** [sparcs-kaist/sparcs_home#14]
2017-9-3에 올라온 것부터 안됨

**Comment by yujingaya** [comment]
port 15693 을 빼면 제대로 다운로드 되는걸 확인.
예를 들어, https://sparcs.org:15693/static/seminars/yujingaya_1505817783992.pdf 이 주어진 링크인데,
https://sparcs.org/static/seminars/yujingaya_1505817783992.pdf 로 다운로드 받으면 정상적으로 다운로드 됨

**Comment by yujingaya** [comment]
2017-09-03 이전의 자료도 포트를 떼면 제대로 다운로드 되는 것을 확인.

localconfig.js 수정이 필요한 상황으로 보임.

**Comment by luaneyed** [comment]
3330a05f091e8760696a4275d186fe345ec75614

mongodb에서 최신 세미나들 직접 port 제거함
