### ISSUE TITLE
(일시적인?) 회원명부 조회 불가

### ISSUE THREAD

**Issue by combacsa** [sparcs-kaist/sparcs_home#16]
https://sparcs.org/members 접근시, 멤버 목록을 불러오는 중입니다... 라는 문구만 표시되고 더 이상 진전이 없습니다. 2018년 1월 11일 13시 48분 현재.

**Comment by luaneyed** [comment]
@combacsa 전 잘 보이네요.. 다시 한 번 확인 부탁드립니다!

**Comment by combacsa** [comment]
2018년 1월 12일 16시 10분 현재 잘 보이네요... 감사합니다. :)
